collection_pop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("users/", include("django.contrib.auth.urls")),
    path("figurines/", include("figurines.urls", namespace="figurines")),
    path("legal_notice/", views.legal_notice, name="legal_notice"),
    path("contact_us/", views.contact_us, name="contact_us"),
    path("who_are_we/", views.who_are_we, name="who_are_we"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

figurines/urls.py
from django.urls import path

from . import views

app_name = "figurines"

urlpatterns = [
    path("add_figurine/", views.add_figurine, name="add_figurine"),
    path("collection/", views.collection_user, name="collection"),
    path("search/", views.search, name="search"),
    path("did_you_see/", views.did_you_see, name="did_you_see"),
    path("post_detail/<int:id_post>/", views.post_detail, name="post_detail"),
    path("create_question", views.create_question, name="create_question"),
    path(
        "create_question/<int:id_post>",
        views.create_question,
        name="create_question",
    ),
    path("delete_figurine", views.delete_figurine, name="delete_figurine"),
    path("report_post/<int:id_post>", views.report, name="report"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path("profile/", views.profile, name="profile"),
    path("create_account", views.create_account, name="create_account"),
    path("del_user", views.del_user, name="del_user"),
    path("friends_list/", views.friends_list, name="friends_list"),
    path("add_friend", views.add_friend, name="add_friend"),
    path("accept_request", views.accept_request, name="accept_request"),
    path("remove_friend", views.remove_friend, name="remove_friend"),
    path("friends_figurine/<int:id>", views.friends_figurine, name="friends_figurine"),
    path(
        "friends_figurine_search/",
        views.friends_figurine_search,
        name="friends_figurine_search",
    ),
]

figurines/models.py
from django.conf import settings
from django.db import models


class Category(models.Model):

    name = models.CharField(max_length=200, default=None)

    def __str__(self):
        return self.name


class Figurine(models.Model):

    figurine_number = models.BigIntegerField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    picture_figurine = models.ImageField(upload_to='', null=True, blank=True)
    user = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
    )

    def __str__(self):
        return str(self.name)

    def __repr__(self):
        return repr(self.name)

class DidYouSee(models.Model):

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE
    )
    title = models.CharField(max_length=100)
    text = models.TextField(null=True)
    date = models.DateField(auto_now=True, verbose_name="Date de parution")
    datetime = models.DateTimeField(auto_now=True)
    parent = models.ForeignKey(
        "DidYouSee",
        on_delete=models.CASCADE,
        blank=True,
        null=True,
    )
    report = models.BooleanField(default=False)

    class Meta:
        verbose_name = "article"
        ordering = ['-datetime']

    def __str__(self):
        return self.title

figurines/forms.py
from django import forms
from django.forms import ModelForm

from figurines.models import Category, DidYouSee, Figurine


class CustomAddFigurineCreationForm(ModelForm):
    name = forms.CharField(
        label="Nom de la figurine",
        widget=forms.TextInput(attrs={'placeholder': 'Nom de la figurine *'}),
    )

    figurine_number = forms.IntegerField(
        label="Numéro de la figurine",
        widget=forms.NumberInput(
            attrs={'placeholder': 'Numéro de la figurine *'}
        ),
    )

    category = forms.CharField(
        label="Categorie de la figurine",
        widget=forms.TextInput(attrs={'placeholder': 'Catégorie *'}),
    )

    picture_figurine = forms.ImageField(
        label="Photo de la figurine",
        required=False,
        widget=forms.FileInput(attrs={'class': 'input-file'}),
    )

    class Meta:
        model = Figurine
        fields = ("figurine_number", "category", "name", "picture_figurine")

    def clean(self, commit=True):
        category_name = self.cleaned_data.get('category')
        try:
            category = Category.objects.get(name__iexact=category_name)
        except Category.DoesNotExist:
            category = Category.objects.create(name=category_name)

        self.cleaned_data['category'] = category
        return super(CustomAddFigurineCreationForm, self).clean()


class CustomCommentCreationForm(ModelForm):
    title = forms.CharField(
        label="Titre",
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'Titre *'}
        ),
    )

    text = forms.CharField(
        label="Titre",
        widget=forms.Textarea(
            attrs={'class': 'form-control', 'placeholder': 'Texte *'}
        ),
    )

    class Meta:
        model = DidYouSee
        fields = (
            "title",
            "text",
        )

figurines/views.py
from django.contrib.auth.decorators import login_required
from django.core.mail import EmailMessage
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CustomAddFigurineCreationForm, CustomCommentCreationForm
from .models import DidYouSee, Figurine


@login_required(login_url='/users/login/')
def add_figurine(request):
    """Django View add a figurine to his collection"""
    user = request.user
    if request.method == 'POST':
        form = CustomAddFigurineCreationForm(request.POST, request.FILES)
        if form.is_valid():
            figurine = form.save()
            figurine.user.add(user)

            return redirect('/figurines/collection')
    else:
        form = CustomAddFigurineCreationForm()
    return render(request, 'figurines/add_figurine.html', {'form': form})


@login_required(login_url='/users/login/')
def collection_user(request):
    """Django View from User Collection"""
    return render(request, 'figurines/collection.html')


@login_required(login_url='/users/login/')
def search(request):
    """Django View collection figurine finder"""
    user = request.user

    if request.method == 'GET':
        if request.GET.get('all'):
            figurines_list = user.figurine_set.all()
        else:
            query = request.GET['q']
            figurines_list = user.figurine_set.filter(name__icontains=query)
    else:
        redirect('/figurines/collection/')
    return render(
        request, 'figurines/search.html', {'figurines_list': figurines_list}
    )


@login_required(login_url='/users/login/')
def did_you_see(request):
    """Django View of the section that viewed"""
    questions = [
        post for post in DidYouSee.objects.all() if post.id == post.parent.id
    ]
    return render(
        request, 'figurines/did_you_see.html', {'questions': questions}
    )


@login_required(login_url='/users/login/')
def post_detail(request, id_post):
    """Django View response to a figurine search"""
    main_post = get_object_or_404(DidYouSee, id=id_post)
    responses = DidYouSee.objects.filter(parent=main_post).exclude(
        id=main_post.id
    )

    context = {
        'main_post': main_post,
        'responses': responses,
    }

    return render(request, 'figurines/post_detail.html', context)


@login_required(login_url='/users/login/')
def create_question(request, id_post=None):
    """Django View for creating a question"""
    if request.method == 'POST':
        form = CustomCommentCreationForm(request.POST)
        if form.is_valid():
            annonce = form.save(commit=False)
            annonce.author = request.user
            annonce.save()

            if id_post:
                post = get_object_or_404(DidYouSee, id=id_post)
                annonce.parent = post
                mail_user = annonce.parent.author.email
                mail = EmailMessage(
                    "Bonjour !",
                    "Une Réponse a été posté sur votre commentaire de recherche !",
                    to=[mail_user],
                )
                mail.send()

            else:
                annonce.parent = annonce

            annonce.save()

            return redirect('/figurines/did_you_see/')
    else:
        form = CustomCommentCreationForm()
    return render(request, 'figurines/create_question.html', {'form': form})


@login_required(login_url='/users/login/')
def delete_figurine(request):
    """Django deletion view of a figurine"""
    if request.method == 'POST':
        user = request.user
        id_figurine = request.POST.get("id_figurine")
        figurine = Figurine.objects.get(id=id_figurine)
        figurine.delete()
        return redirect('/figurines/collection/')


def report(request, id_post):
    """Django seen from a post"""
    post = get_object_or_404(DidYouSee, id=id_post)
    post.report = True
    post.save()
    mail = EmailMessage(
        "Urgent !", "Un post a été signalé !", to=['benjamin.rejaud@gmail.com']
    )
    mail.send()
    return render(request, 'figurines/report.html')

figurines/templates/figurines/add_figurine.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<section id="addfigurine">
    <div class="container">
        <form method="post" enctype="multipart/form-data" class="custom-forms">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="row align-items-stretch">
                <div class="col">
                    <div class="form-group">
                        {{ form.figurine_number }}
                        {{ form.figurine_number.errors }}
                        <p class="help-block text-danger"></p>

                        {{ form.category }}
                        {{ form.category.errors }}
                        <p class="help-block text-danger"></p>

                        {{ form.name }}
                        {{ form.name.errors }}
                        <p class="help-block text-danger"></p>

                        <label for="{{ form.picture_figurine.id_for_label }}"
                            class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom">Choisir une
                            image</label>
                        {{ form.picture_figurine }}
                        {{ form.picture_figurine.errors }}
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
            </div>
            <button class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom"
                type="submit" id="button-submit-addfigurine">Valider</button>
        </form>
    </div>
</section>
{% endblock content %}

figurines/templates/figurines/collection.html
{% extends "base.html" %}


{% block content %}

<section class="page-section" id="collection">
    <div class="container">
        <div class="text-center">
            <h3 class="textcustom text-muted">Recherche les figurines de ta collection via le nom d'une figurine.</h3>
            <br>
            <form action="{% url 'figurines:search' %}#search" method="get">
                <div>
                <input type="search" id="collection_user" class="collection_user" name="q">
                <br>
                <br>
                <button class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom">Rechercher</button>
                </div>
            </form>
            <br>
            <form action="{% url 'figurines:search' %}#search" method="get">
                <div>
                <input type="hidden" value="all" id="collection_user" class="collection_user" name="all">
                <button class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom">Voir la collection complète</button>
                </div>
            </form>
            <br>
            <a class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom" id="id-addfigurine" href="{% url 'figurines:add_figurine' %}#addfigurine">Ajouter une figurine à la collection</a>
        </div>
    </div>
</section>
{% endblock content %}

figurines/templates/figurines/create_question.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<section class="page-section" id="contact">
    <div class="container">
        <div class="text-center">
            <h3 class="section-heading text-uppercase">Tu cherche une figurine ? alors poste une annonce !</h3>
        </div>
        <br>
        <form method="post" id="contactForm" name="sentMessage" novalidate="novalidate">
            {% csrf_token %}
            <div class="row align-items-stretch mb-5">
                <div class="col-md-6">
                    <div class="form-group">
                        {{ form.title }}
                        {{ form.title.errors }}
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group form-group-textarea mb-md-0">
                        {{ form.text }}
                        {{ form.text.errors }}
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
            </div>
            <div class="text-center">
                <div id="success"></div>
                <button class="btn btn-primary btn-xl text-uppercase textcolorcustom" id="sendMessageButton" type="submit">Valider</button>
            </div>
        </form>
    </div>
  </section>
{% endblock content %}

figurines/templates/figurines/did_you_see.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<section class="page-section" id="didyousee">
    <div class="container">
        <div class="text-center">
            <h3 class="textcustom text-muted">Tu cherche une figurine ? alors poste une annonces !</h3>
            <h3 class="textcustom text-muted">Ou répond à un utilisateur ! tu à juste à cliquer sur le titre de l'annonce .</h3>
            <br>
            <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger textcolorcustom" href="{% url 'figurines:create_question' %}">Ajouter une annonce</a>
        </div>
        <br>
        <div class="text-center" style="list-style-type:none">
            {% for question in questions %}
            <li>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        {{ question.author }} - {{ question.date }}
                    </div>
                    <div class="timeline-body"><h4><a href="{% url 'figurines:post_detail' id_post=question.id %}#post_detail" style="color:#33BEFF">{{question.title }}</a></h4></div>
                    <div class="timeline-body"><p class="text-muted">{{ question.text }}</p></div>
                </div>
            </li>
            <hr width="200px" color="#D89744">
            <br>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

figurines/templates/figurines/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<section class="page-section" id="post_detail">
    <div class="container">
        <div class="text-center">
            <h3 class="section-subheading">Tu à vue une figurine ? alors répond à une annonces !</h3>
            
        </div>
        <br>
        <ul class="timeline">
            <li>
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        {{ main_post.author }} - {{ main_post.date }}
                    </div>
                    <div class="timeline-body">
                        <h4>{{ main_post.title }}</h4>
                    </div>
                    <div class="timeline-body">
                        <p class="text-muted">{{ main_post.text }}</p>
                    </div>
                    <form action="{% url 'figurines:create_question' id_post=main_post.id %}" method="post">
                        {% csrf_token %}
                        <button class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom" type="submit">Répondre</button>
                    </form>
                        <div>
                            <br>
                            <form action="{% url 'figurines:report' id_post=main_post.id %}#report" method="post">
                                {% csrf_token %}
                                <button class="button-report" type="submit">Signaler</button>
                            </form>
                        </div>
                </div>
            </li>
            {% for response in responses %}
            <li class="timeline-inverted">
                <div class="timeline-panel">
                    <div class="timeline-heading">
                        {{ response.author }} - {{ response.date }}
                    </div>
                    <div class="timeline-body">
                        <h4>{{ response.title }}</h4>
                    </div>
                    <div class="timeline-body">
                        <p class="text-muted">{{ response.text }}</p>
                    </div>
                    <div>
                        <form action="{% url 'figurines:report' id_post=main_post.id %}#report" method="post">
                            {% csrf_token %}
                            <button class="button-report" type="submit">Signaler</button>
                        </form>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock content %}

figurines/templates/figurines/report.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<section class="page-section" id="report">
    <div class="container">
        <hr width="200px" color="#D89744">
        <br>
        <div class="text-center">
            <h3 class="textcustom text-muted">Merci pour le signalement, votre demande va être étudiée .</h3>
        </div>
        <br>
        <hr width="200px" color="#D89744">
    </div>
</section>
{% endblock content %}

figurines/templates/figurines/result_search.html
{% extends "base.html" %}


{% block content %}
{% load static %}
{% get_media_prefix as MEDIA_PREFIX %}

{% if figurines_list %}
<div class="container-fluid img-f">
    {% for figurine in figurines_list %}
    <img src="{{ MEDIA_PREFIX }}{{ figurine.picture_figurine }}" alt="Image du produit">
    {% endfor %}
    {% else %}
        <h2 class="text-center mt-0 font-custom-title">
            Pas de résultat pour {{ figurine.name }}.
        </h2>
    {% endif %}
</div>
{% endblock content %}

figurines/templates/figurines/search.html
{% extends "base.html" %}


{% block content %}
{% load static %}
{% get_media_prefix as MEDIA_PREFIX %}

{% if figurines_list %}
<section class="page-section bg-light" id="search">
    
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-10">
                <div class="container">
                    <div class="row justify-content-center">
                        {% for figurine in figurines_list %}
                        <div class="col-lg-4 col-md-12">
                            <ul>
                                <div class="team-member">
                                    <img class="mx-auto rounded-circle img-figurine" src="{{ MEDIA_PREFIX }}{{ figurine.picture_figurine }}" alt="Image du produit">
                                    <div class="textcustomfigurine">Catégorie : {{ figurine.category }}</div>
                                    <div class="textcustomfigurine">Nom de la figurine: {{ figurine.name }}</div>
                                    <div class="textcustomfigurine">Numéro de la figurine: {{ figurine.figurine_number }}</div>
                                    <form action="{% url 'figurines:delete_figurine' %}" method="POST">{% csrf_token %}<button
                                        class="button-del" type="submit"><i class="fa fa-times" aria-hidden="true"></i></i>
                                    </button>&nbsp Supprimer
                                    <input type="hidden" id="id_figurine" name="id_figurine" value="{{ figurine.pk }}">
                                    </form>
                                    <br>
                                    <br>
                                </div>
                            </ul>
                        </div>
                        {% endfor %}
                    </div>
                    {% else %}
                    <section class="omg" id="search">
                        <h2 class="textomg">
                            Pas de résultat.
                        </h2>
                </section>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}