collection_pop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("users/", include("django.contrib.auth.urls")),
    path("figurines/", include("figurines.urls", namespace="figurines")),
    path("legal_notice/", views.legal_notice, name="legal_notice"),
    path("contact_us/", views.contact_us, name="contact_us"),
    path("who_are_we/", views.who_are_we, name="who_are_we"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

figurines/urls.py
from django.urls import path

from . import views

app_name = "figurines"

urlpatterns = [
    path("add_figurine/", views.add_figurine, name="add_figurine"),
    path("collection/", views.collection_user, name="collection"),
    path("search/", views.search, name="search"),
    path("did_you_see/", views.did_you_see, name="did_you_see"),
    path("post_detail/<int:id_post>/", views.post_detail, name="post_detail"),
    path("create_question", views.create_question, name="create_question"),
    path(
        "create_question/<int:id_post>",
        views.create_question,
        name="create_question",
    ),
    path("delete_figurine", views.delete_figurine, name="delete_figurine"),
    path("report_post/<int:id_post>", views.report, name="report"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path("profile/", views.profile, name="profile"),
    path("create_account", views.create_account, name="create_account"),
    path("del_user", views.del_user, name="del_user"),
    path("friends_list/", views.friends_list, name="friends_list"),
    path("add_friend", views.add_friend, name="add_friend"),
    path("accept_request", views.accept_request, name="accept_request"),
    path("remove_friend", views.remove_friend, name="remove_friend"),
    path("friends_figurine/<int:id>", views.friends_figurine, name="friends_figurine"),
    path(
        "friends_figurine_search/",
        views.friends_figurine_search,
        name="friends_figurine_search",
    ),
]

users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """User models Django."""

    pass

users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'placeholder': "Nom d'utilisateur *"}),
    )

    email = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={'placeholder': "Adresse mail *"}),
    )

    password1 = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={'placeholder': "Mot de passe *"}),
    )

    password2 = forms.CharField(
        label="",
        widget=forms.PasswordInput(
            attrs={'placeholder': "Confirmation du mot de passe *"}
        ),
    )

    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ("username", "email")

users/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render, reverse
from figurines.models import Figurine
from friendship.exceptions import AlreadyExistsError, AlreadyFriendsError
from friendship.models import Friend, FriendshipRequest

from users.models import User

from .forms import CustomUserCreationForm


@login_required(login_url='/users/login/')
def profile(request):
    """Django view profile page"""
    return render(request, 'users/profile.html')


def create_account(request):
    """Django view account creation"""
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/users/profile')
    else:
        form = CustomUserCreationForm()
    return render(request, 'users/create_account.html', {'form': form})


@login_required(login_url='/users/login/')
def del_user(request):
    """Django view del user"""

    if not request.user.is_superuser:
        username = request.user
        user = User.objects.get(username=username)
        user.delete()

    return redirect('/')


@login_required(login_url='/users/login/')
def friends_list(request):
    """Django view friends list page"""
    friends = Friend.objects.friends(request.user)
    friend_requests = Friend.objects.unrejected_requests(user=request.user)
    friend_request_pending = [
        User.objects.get(pk=friend.from_user_id) for friend in friend_requests
    ]

    try:
        user_found = request.session['user_found']
        del request.session['user_found']
    except KeyError:
        user_found = None

    try:
        user_not_found = request.session['user_not_found']
        del request.session['user_not_found']
    except KeyError:
        user_not_found = None
    
    try:
        user_already_added = request.session['user_already_added']
        del request.session['user_already_added']
    except KeyError:
        user_already_added = None

    context = {
        'friends': friends,
        'friend_requests': friend_requests,
        'friend_request_pending': friend_request_pending,
        'user_not_found': user_not_found,
        'user_found': user_found,
        'user_already_added': user_already_added,
    }

    return render(request, 'users/friends_list.html', context)


@login_required(login_url='/users/login/')
def add_friend(request):
    """Django view add friend"""
    try:
        username = request.POST['username']
        other_user = User.objects.get(username=username)
        add_friend = Friend.objects.add_friend(request.user, other_user)
        request.session[
            'user_found'
            ] = f"Demande d'amis envoyée !"

    except User.DoesNotExist:
        request.session[
            'user_not_found'
        ] = f'Utilisateur "{username}" inconnu.'
        return redirect(reverse('users:friends_list'))
    
    except AlreadyExistsError:
        request.session[
            'user_already_added'
            ] = f"La demande à déjà été envoyée !"
    
    except AlreadyFriendsError:
        request.session[
            'user_already_added'
            ] = f"La demande à déjà été envoyée !"

    return redirect('/users/friends_list/')


@login_required(login_url='/users/login/')
def accept_request(request):
    """Django view accept request add friend"""
    user = request.user
    other_user_id = request.POST.get('other_user_id')
    friend_request = FriendshipRequest.objects.get(
        from_user=other_user_id, to_user=user.id
    )

    user_choice = request.POST.get('user_choice')

    if user_choice == "Accepted":
        friend_request.accept()
    else:
        friend_request.reject()
        friend_request.delete()

    return redirect('/users/friends_list/')


@login_required(login_url='/users/login/')
def remove_friend(request):
    """Django view remove friend the friend list"""
    user = request.user
    other_user_id = request.POST.get('other_user_id')

    other_user = get_object_or_404(User, id=other_user_id)
    user_del = Friend.objects.remove_friend(request.user, other_user)

    return redirect('/users/friends_list/')


@login_required(login_url='/users/login/')
def friends_figurine(request, id):
    friend = get_object_or_404(User, id=id)
    return render(request, 'users/friends_figurine.html', {'friend': friend})


@login_required(login_url='/users/login/')
def friends_figurine_search(request):
    id = request.GET['friend_id']
    friends_selected = User.objects.get(id=id)

    if Friend.objects.are_friends(request.user, friends_selected):
        if request.GET.get('q'):
            query = request.GET['q']
            figurines_list = friends_selected.figurine_set.filter(name__icontains=query)
        elif request.GET.get('all'):
            figurines_list = friends_selected.figurine_set.all()          
        else:
            return redirect('/users/friends_list/')

        return render(
            request,
            'users/friends_figurine_search.html',
            {'figurines_list': figurines_list}
        )

    else:
        return redirect('/users/friends_list/')

users/templates/users/collection.html
{% extends "base.html" %}


{% block content %}
<h2>Ma collection de figurine .</h2>
<form action="{% url 'users:collection' %}" method="get">
    <div>
    <input type="search" id="collection_user" class="collection_user" name="q">
    <button>Rechercher</button>
    </div>
</form>
<br>

<a href="{% url 'figurines:add_figurine' %}"><button>Ajouter une figurine à la collection</button></a>
{% endblock content %}

users/templates/users/create_account.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<br>
<div class="text-center" id="login">
    <span class="fa-stack fa-4x">
        <i class="fas fa-circle fa-stack-2x text-primary"></i>
        <i class="fas fa-laptop fa-stack-1x fa-inverse"></i>
    </span>
    <br>
    <h2 class="textcustom">
        Création compte utilisateur
    </h2>
    <div class="container">
        <form method="post" class="custom-forms">
            {% csrf_token %}
            <div class="row align-items-stretch">
                <div class="col">
                    <div class="form-group">
                        {{ form.username }}
                        {{ form.username.errors }}
                        <p class="help-block text-danger"></p>

                        {{ form.email }}
                        {{ form.email.errors }}
                        <p class="help-block text-danger"></p>

                        {{ form.password1 }}
                        {{ form.password1.errors }}
                        <p class="help-block text-danger"></p>

                        {{ form.password2 }}
                        {{ form.password2.errors }}
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
            </div>
            <button class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom" type="submit">Créer un compte</button>
        </form>
    </div>
</div>
{% endblock content %}

users/templates/users/did_you_see.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h2>Tu cherche une figurine ? alors poste une annonce !</h2>
<section>
    <form method="post" class="custom-forms">
        {% csrf_token %}
        {{ form|crispy }}
        <br>
        <button type="submit">Valider</button>
    </form>
</section>
{% endblock content %}

users/templates/users/friends_figurine.html
{% extends "base.html" %}
{% block content %}
<section class="page-section" id="collection-friends">
    <div class="container">
        <div class="text-center">
            <h3 class="textcustom text-muted">Recherches une figurine dans la collection de {{ friend.username }} via le nom de la figurine.</h3>
            <br>
            <form action="{% url 'users:friends_figurine_search' %}#search" method="get">
                <div>
                <input type="search" id="collection_friends" class="collection_user" name="q">
                <br>
                <br>
                <input type="hidden" id="friend_id" class="collection_user" name="friend_id" value="{{ friend.id }}">
                <button class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom">Rechercher</button>
                </div>
            </form>
            <br>
            <form action="{% url 'users:friends_figurine_search' %}#search" method="get">
                <div>
                <input type="hidden" id="collection_friends" class="collection_user" value="all" name="all">
                <input type="hidden" id="friend_id" class="collection_user" name="friend_id" value="{{ friend.id }}">
                <button class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom">Voir la collection complète</button>
                </div>
            </form>
        </div>
    </div>
</section>

{% endblock content %}

users/templates/users/friends_figurine_search.html
{% extends "base.html" %}

{% block content %}
{% load static %}
{% get_media_prefix as MEDIA_PREFIX %}

{% if figurines_list %}
<section class="page-section bg-light" id="search">
    
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-10">
                <div class="container">
                    <div class="row justify-content-center">
                        {% for figurine in figurines_list %}
                        <div class="col-lg-4 col-md-12">
                            <ul>
                                <div class="team-member">
                                    <img class="mx-auto rounded-circle img-figurine" src="{{ MEDIA_PREFIX }}{{ figurine.picture_figurine }}" alt="Image du produit">
                                    <div class="textcustomfigurine">Catégorie : {{ figurine.category }}</div>
                                    <div class="textcustomfigurine">Nom de la figurine: {{ figurine.name }}</div>
                                    <div class="textcustomfigurine">Numéro de la figurine: {{ figurine.figurine_number }}</div>
                                    <br>
                                    <br>
                                </div>
                            </ul>
                        </div>
                        {% endfor %}
                    </div>
                    {% else %}
                    <section class="omg" id="search">
                        <h2 class="textomg">
                            Pas de résultat.
                        </h2>
                </section>
                {% endif %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

users/templates/users/friends_list.html
{% extends "base.html" %}

{% block content %}


<div class="container">
    <br>
    <div class="text-center" id="friends-list">
        {% if user_not_found %}
            {{ user_not_found }}
        {% endif %}
        {% if user_found %}
            {{ user_found }}
        {% endif %}
        {% if user_already_added %}
            {{ user_already_added }}
        {% endif %}
        <h3 class="textcustom text-muted">Recherche un amis via sont pseudo .</h3>
        <div class="container">
            <form action="{% url 'users:add_friend' %}" method="POST">
                {% csrf_token %}
                <input type="search" id="collection_user" class="collection_user" name="username"
                    placeholder="Entre un pseudo">
                <br>
                <br>
                <button class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom" id="search-friend">Rechercher</button>
            </form>
        </div>
    </div>
    <br>
    <div class="container box-shadow">
        <div>
            <br>
            <h2>Liste d'amis :</h2>
        </div>
        <br>
        {% for friend in friends %}
        <div class="row">
            <div class="col text-center">
                <p><a class="textcustom textcolorcustom" href="{% url 'users:friends_figurine' friend.id %}#collection-friends">{{ friend.username }}</a></p>
            </div>
            <div class="col text-center">
                <form action="{% url 'users:remove_friend' %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" id="other_user_id" name="other_user_id" value="{{ friend.id }}">
                    <button class="button-del" type="submit"><i class="fa fa-times" aria-hidden="true"></i></button>
                </form>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

<br>
<div class="container">
    <div>
        <br>
        <h2>Demandes d'amis :</h2>
    </div>
    <hr max-width="700px" color="#29A4FE">
    <br>

    {% for friend in friend_request_pending %}
    <div class="row">
        <div class="col text-center">
            <p class="textcustom">{{ friend }}</p>
        </div>
        <div class="col text-center">
            <form name="friend_request" action="{% url 'users:accept_request' %}" method="post">
                {% csrf_token %}
                <input type="hidden" id="other_user_id" name="other_user_id" value="{{ friend.id }}">
                <input class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom" type="submit"
                    name="accept" id="accept" value="Valider" onclick="acceptFunction()">
                <input class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom"
                    style="background-color: #DE2F2F;" type="submit" name="reject" id="reject" value="Refuser"
                    onclick="rejectFunction()">
                <input type="hidden" id="user_choice" name="user_choice" value="">
            </form>
            <script>
                function acceptFunction() {
                    document.friend_request.user_choice.value = "Accepted";
                }
                function rejectFunction() {
                    document.friend_request.user_choice.value = "Rejected";
                }
            </script>
            <br>
        </div>
    </div>
    {% endfor %}

</div>
</div>

{% endblock content %}

users/templates/users/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<br>
<div class="text-center" id="login">
    <span class="fa-stack fa-4x">
        <i class="fas fa-circle fa-stack-2x text-primary"></i>
        <i class="fas fa-laptop fa-stack-1x fa-inverse"></i>
    </span>
    <br>
    <h2 class="textcustom">
        Connexion utilisateur
    </h2>
    <div class="container">
        <form method="post" enctype="multipart/form-data" class="custom-forms">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="row align-items-stretch">
                <div class="col">
                    <div class="form-group">
                        {{ form.username }}
                        {{ form.username.errors }}
                        <p class="help-block text-danger"></p>

                        {{ form.password }}
                        {{ form.password.errors }}
                        <p class="help-block text-danger"></p>
                    </div>
                </div>
            </div>
            <button class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom" type="submit" id="button-submit">Se connecter</button>
        </form>
        <br>
    <a class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom" href="{% url 'password_reset' %}#reset-pages-1">Mot de passe oublié ?</a>
    </div>
</div>
{% endblock content %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}

<section class="page-section" id="profile">
    <div class="container">
        <div class="text-center">
            <h2 class="section-heading">Détails du compte</h2>
        </div>
        <div class="row text-center">
            <div class="col-md-4">
            </div>
            <div class="col-md-4">
                <span class="fa-stack fa-4x">
                    <i class="fas fa-circle fa-stack-2x text-primary"></i>
                    <i class="fas fa-laptop fa-stack-1x fa-inverse"></i>
                </span>
                <h3 class="textcustom text-muted">Email du compte : {{user.email}}</h3>
                <h3 class="textcustom text-muted">Nom d'utilisateur : {{user.username}}</h3>
                {% if user.is_superuser %}
                    <form action="{% url 'admin:index' %}" method="post">
                        {% csrf_token %}
                        <button class="button-report" type="submit">Espace Admin</button>
                    </form>
                {% endif %}
                <br>
                <form action="{% url 'users:del_user' %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary text-uppercase js-scroll-trigger textcolorcustom" type="submit">Supprimer mon compte</button>
                </form>
            </div>
            <div class="col-md-4">
            </div>
        </div>
    </div>
</section>
{% endblock content %}