collection_pop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('admin/', admin.site.urls),
    path("users/", include("users.urls", namespace="users")),
    path("users/", include("django.contrib.auth.urls")),
    path("figurines/", include("figurines.urls", namespace="figurines")),
    path("legal_notice/", views.legal_notice, name="legal_notice"),
    path("contact_us/", views.contact_us, name="contact_us"),
    path("who_are_we/", views.who_are_we, name="who_are_we"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

figurines/urls.py
from django.urls import path

from . import views

app_name = "figurines"

urlpatterns = [
    path("add_figurine/", views.add_figurine, name="add_figurine"),
    path("collection/", views.collection_user, name="collection"),
    path("search/", views.search, name="search"),
    path("did_you_see/", views.did_you_see, name="did_you_see"),
    path("post_detail/<int:id_post>/", views.post_detail, name="post_detail"),
    path("create_question", views.create_question, name="create_question"),
    path(
        "create_question/<int:id_post>",
        views.create_question,
        name="create_question",
    ),
    path("delete_figurine", views.delete_figurine, name="delete_figurine"),
    path("report_post/<int:id_post>", views.report, name="report"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(),
        name="logout",
    ),
    path("profile/", views.profile, name="profile"),
    path("create_account", views.create_account, name="create_account"),
    path("del_user", views.del_user, name="del_user"),
    path("friends_list/", views.friends_list, name="friends_list"),
    path("add_friend", views.add_friend, name="add_friend"),
    path("accept_request", views.accept_request, name="accept_request"),
    path("remove_friend", views.remove_friend, name="remove_friend"),
    path("friends_figurine/<int:id>", views.friends_figurine, name="friends_figurine"),
    path(
        "friends_figurine_search/",
        views.friends_figurine_search,
        name="friends_figurine_search",
    ),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <title>{% block title %}{% endblock title %}</title>
  <!-- Font Awesome icons (free version)-->
  <link rel="icon" type="image/png" href="/static/dist/assets/img/favicon.png" />
  <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"/> -->
  <!-- Google fonts-->
  <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
  <link href="https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic" rel="stylesheet"
    type="text/css" />
  <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
  <!-- Core theme CSS (includes Bootstrap)-->
  <link href="{% static 'dist/css/styles.css' %}" rel="stylesheet" />
</head>

<body id="page-top">
  <!-- Navigation-->
  {% block nav %}
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top"></a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse"
        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false"
        aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars ml-1"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav text-uppercase ml-auto">
          <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home' %}">Accueil</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link js-scroll-trigger" id="logout-link" href="{% url 'users:logout' %}">Deconnexion</a></li>
          <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'users:profile' %}#profile">Mon
              Compte</a></li>
          <li class="nav-item"><a class="nav-link js-scroll-trigger"
              id="id-collection" href="{% url 'figurines:collection' %}#collection">Ma collection</a></li>
          <li class="nav-item"><a class="nav-link js-scroll-trigger"
              id="id-friends-list"  href="{% url 'users:friends_list' %}#friends-list">Liste d'amis</a></li>
          <li class="nav-item"><a class="nav-link js-scroll-trigger"
              href="{% url 'figurines:did_you_see' %}#didyousee">Qui à vue ?</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link js-scroll-trigger" id="login-link" href="{% url 'users:login' %}#login">Connexion</a>
          </li>
          <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'users:create_account' %}">Créer mon
              compte</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  {% endblock nav %}
  <!-- Masthead-->
  {% block header %}
  <header class="masthead">
    <div class="container">
      <div class="masthead-subheading textcolorcustom">Tu cherches à répertorier ta collection de figurine Pop, alors
        bienvenue!</div>
      {% if user.is_authenticated %}
      <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger textcolorcustom"
        href="{% url 'figurines:collection' %}#collection">Ma collection</a>
      {% else %}
      <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger textcolorcustom"
        href="{% url 'users:login' %}#login">Connexion</a>
      <br>
      <br>
      <a class="btn btn-primary btn-xl text-uppercase js-scroll-trigger textcolorcustom"
        href="{% url 'users:create_account' %}">Créer mon compte</a>
      {% endif %}
    </div>
  </header>
  {% endblock header %}

  {% block content %}
  {% endblock content %}
  <!-- Footer-->
  {% block footer %}
  <footer class="footer py-4">
    <div class="container">
      <div class="align-items-center">
        <div class="text-center">
          <a class="mr-3" href="{% url 'legal_notice' %}#legalnotice" style="color:black">Mentions légales</a>
        </div>
        <div class="text-center">
          <a class="mr-3" href="{% url 'contact_us' %}#contact-us" style="color:black">Nous contacter</a>
        </div>
        <div class="text-center">
          <a class="mr-3" href="{% url 'who_are_we' %}#who-are-we" style="color:black">Qui sommes-nous ?</a>
        </div>
        <div class="text-center">Copyright © 2020 Collection Pop</div>
      </div>
    </div>
  </footer>
  {% endblock footer %}
  {% block bottom_script %}
  <!-- Bootstrap core JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
  <!-- Third party plugin JS-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'jquery.ihavecookies.js' %}"></script>
    <script type="text/javascript">
    var options = {
        title: '&#x1F36A; Accepter les cookies et la politique de confidentialité ?',
        message: 'En poursuivant la navigation sur le site, vous acceptez le dépôt de cookies et autres tags.',
        delay: 600,
        expires: 1,
        link: '#privacy',
        onAccept: function(){
            var myPreferences = $.fn.ihavecookies.cookie();
            console.log('Yay! The following preferences were saved...');
            console.log(myPreferences);
        },
        uncheckBoxes: true,
        acceptBtnLabel: 'Accepter les cookies',
        moreInfoLabel: '',
        cookieTypesTitle: 'Sélectionnez les cookies que vous souhaitez accepter',
        fixedCookieTypeLabel: 'Essentiel',
        fixedCookieTypeDesc: 'These are essential for the website to work correctly.'
    }

    $(document).ready(function() {
        $('body').ihavecookies(options);

        if ($.fn.ihavecookies.preference('marketing') === true) {
            console.log('This should run because marketing is accepted.');
        }

        $('#ihavecookiesBtn').on('click', function(){
            $('body').ihavecookies(options, 'reinit');
        });
    });

    </script>
  <script src="{% static 'dist/js/scripts.js' %}"></script>
{% endblock bottom_script %}
</body>

</html>